Added #[generate(Debug)] feature
diondokter/device-driver pull request #10
Opened 2021-04-29 20:00 UTC by diondokter

Closes #8 

You can now do this:

```rust
implement_registers!(
    MyDevice.registers<u8> = {
        // (comments must go first)
        #[generate(Debug)]              // <- new!
        id(RO, 0, 3) = MSB {
            manufacturer: u16:LE as Manufacturer = RW 0..16,
            version: u8:NE = RO 16..20,
            edition: u8:BE = RO 20..24,
        },
    }
);
```

Then we can:

```rust
let id = device.registers().id().read()?;
println!("{:?}", id);
```
```
id::R { raw: 0x010065, manufacturer: Ok(CarmineCrystal), version: 6, edition: 5 }
```

The generate attribute is optional. If you don't add it to the register, the output is now better too:
```
id::R { raw: 0x010065 }
```

When opting in, all field types must impl Debug.

This attribute syntax can be used later for other things as well.

2021-04-29 20:19 UTC, diondokter commented
I'm now just noticing it... The field values that are just a number are in decimal. All other numbers are Hex. Will this be a problem?
It's only the raw bit values that are hex and they're all prepended with `0x`, so I think that's fine.
In the end you're supposed to leave numbers as numbers. Anywhere where the bits are important (so you'd want to see the hex fmt) should be encoded in enums anyways.

2021-05-01 17:27 UTC, korken89 requested changes
These need to be changed so paths are internal to the macro

2021-05-01 17:27 UTC, korken89 commented on src/ll/mod.rs
> +        impl<T: core::fmt::UpperHex + Debug> From<ConversionError<T>> for LowLevelError {
```suggestion
        impl<T: core::fmt::UpperHex + core::fmt::Debug> From<ConversionError<T>> for LowLevelError {
```

2021-05-01 17:27 UTC, korken89 commented on src/ll/register.rs
> +            impl Debug for R {
```suggestion
            impl core::fmt::Debug for R {
```

2021-05-01 17:27 UTC, korken89 commented on src/ll/register.rs
> +            impl Debug for R {
```suggestion
            impl core::fmt::Debug for R {
```

2021-05-01 17:27 UTC, korken89 commented on src/ll/register.rs
> +            impl Debug for R {
```suggestion
            impl core::fmt::Debug for R {
```

2021-05-01 17:27 UTC, korken89 commented on src/ll/register.rs
> +            impl Debug for R {
```suggestion
            impl core::fmt::Debug for R {
```

2021-05-01 17:31 UTC, diondokter commented
Good you spotted that!

2021-05-01 17:33 UTC, korken89 commented
Now it works when I test it!

2021-05-01 17:33 UTC, merged